name: Test GCS Release Bucket
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_gcs_release_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          project_id: ${{ secrets.DBDOT_GCS_RELEASE_BUCKET_PROJECT_ID }}
          credentials_json: ${{ secrets.DBDOT_GCS_RELEASE_BUCKET_CREDENTIALS }}
      - name: Install Gcloud SDK
        uses: google-github-actions/setup-gcloud@e427ad8a34f8676edf47cf7d7925499adf3eb74f # v2.2.1
      - name: Test Gsutil
        run: gsutil ls gs://dbdot-release
      - run: gsutil cp LICENSE gs://dbdot-release/LICENSE
      - run: gsutil rm gs://dbdot-release/LICENSE
