name: manual_msi_build
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Collector Version"
        required: true
        default: "v0.0.1"
      build_amd64:
        description: "Build amd64 MSI"
        type: boolean
        default: true
      build_arm64:
        description: "Build arm64 MSI"
        type: boolean
        default: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        shell: bash
        run: |
          matrix='{"include":[]}'
          if [ "${{ inputs.build_amd64 }}" = "true" ]; then
            matrix=$(echo $matrix | jq -c '.include += [{"arch":"amd64","msi_name":"dynatrace-bindplane-otel-collector-amd64.msi","msi_arch":"x64"}]')
          fi
          if [ "${{ inputs.build_arm64 }}" = "true" ]; then
            matrix=$(echo $matrix | jq -c '.include += [{"arch":"arm64","msi_name":"dynatrace-bindplane-otel-collector-arm64.msi","msi_arch":"arm64"}]')
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-msi:
    uses: ./.github/workflows/build-signed-windows.yml
    with:
      version: ${{ inputs.version }}
      build_amd64: ${{ inputs.build_amd64 }}
      build_arm64: ${{ inputs.build_arm64 }}
    secrets: inherit
